# The name of the scenario is the root of a YAML tree.
test:

  # We must specify how many nodes exist in this scenario. They do not have to
  # be all specified, or even connected, however.
  numnodes: 6

  # Here we can specify (a subset of) the network information, i.e. whether a
  # node is initially connected or not, and the costs and benefits associated
  # with each edge. In this case, they are the parameters for the Bernoulli and
  # gamma distributions.
  #
  # Note that anything omitted here will be set to default values.
  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 }
      2: { p: 0.5, alpha: 1, theta: 2 }
      3: { p: 0.1, alpha: 1, theta: 2 }
      4: { p: 0.1, alpha: 1, theta: 2 }
      5: { p: 0.1, alpha: 1, theta: 2 }
    1:
      connected: false

  # The strategy "broadcast" is used for all nodes, unless specified.
  # This will usually be overridden in the experimental variants configuration,
  # but can also be specified here as follows. You shouldn't usually need to do
  # this, however.
  #
  #node_strategies:
    #0: broadcast

  # Should we output debugging information about the simulation or the nodes?
  debug: false
  node_debug: false

  # We can define events, which occur at the given time and can either be the
  # addition or removal of a node. Each event must have a unique name.
  events:
    delete5:
      time: 2000
      node: 5
      action: remove
    delete4:
      time: 2000
      node: 4
      action: remove
    delete3:
      time: 5000
      node: 3
      action: remove
    addallback1:
      time: 7500
      node: 3
      action: add
    addallback2:
      time: 7500
      node: 4
      action: add
    addallback3:
      time: 7500
      node: 5
      action: add


# Here are some more scenarios.

scenario1:
  numnodes: 3

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.01, alpha: 1, theta: 110 } # node B

  debug: false


scenario2:
  numnodes: 3

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 1, alpha: 1, theta: 0.8 } # node C

  node_strategies:
    0: step
  filename_suffix: step

  debug: false


scenario3:
  numnodes: 4

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.1, alpha: 1, theta: 0.1 } # node D
      3: { p: 1, alpha: 1, theta: 1.8 } # node E

  node_strategies:
    0: step
  filename_suffix: step

  debug: false


# Sudden dynamics scenarios.

scenario12:
  numnodes: 6

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.01, alpha: 1, theta: 110 } # node B
      3: { p: 1, alpha: 1, theta: 0.8 } # node C
      4: { p: 0.1, alpha: 1, theta: 0.1 } # node D
      5: { p: 1, alpha: 1, theta: 1.8 } # node E
    3:
      connected: false
    4:
      connected: false
    5:
      connected: false

  events:
    broadcast-smooth1:
      time: 5000
      node: 2
      action: remove
    broadcast-smooth2:
      time: 5000
      node: 3
      action: add

  node_strategies:
    0: step

  filename_suffix: step

  debug: false


scenario13:
  numnodes: 6

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.01, alpha: 1, theta: 110 } # node B
      3: { p: 1, alpha: 1, theta: 0.8 } # node C
      4: { p: 0.1, alpha: 1, theta: 0.1 } # node D
      5: { p: 1, alpha: 1, theta: 1.8 } # node E
    3:
      connected: false
    4:
      connected: false
    5:
      connected: false

  events:
    broadcast-step1:
      time: 5000
      node: 2
      action: remove
    broadcast-step2:
      time: 5000
      node: 4
      action: add
    broadcast-step3:
      time: 5000
      node: 5
      action: add

  node_strategies:
    0: step

  filename_suffix: step

  debug: false


scenario21:
  numnodes: 6

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.01, alpha: 1, theta: 110 } # node B
      3: { p: 1, alpha: 1, theta: 0.8 } # node C
      4: { p: 0.1, alpha: 1, theta: 0.1 } # node D
      5: { p: 1, alpha: 1, theta: 1.8 } # node E
    2:
      connected: false
    4:
      connected: false
    5:
      connected: false

  events:
    smooth-broadcast1:
      time: 5000
      node: 3
      action: remove
    smooth-broadcast2:
      time: 5000
      node: 2
      action: add

  node_strategies:
    0: step

  filename_suffix: step

  debug: false


scenario23:
  numnodes: 6

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.01, alpha: 1, theta: 110 } # node B
      3: { p: 1, alpha: 1, theta: 0.8 } # node C
      4: { p: 0.1, alpha: 1, theta: 0.1 } # node D
      5: { p: 1, alpha: 1, theta: 1.8 } # node E
    2:
      connected: false
    4:
      connected: false
    5:
      connected: false

  events:
    smooth-step1:
      time: 5000
      node: 3
      action: remove
    smooth-step2:
      time: 5000
      node: 4
      action: add
    smooth-step3:
      time: 5000
      node: 5
      action: add

  node_strategies:
    0: step

  filename_suffix: step

  debug: false


scenario31:
  numnodes: 6

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.01, alpha: 1, theta: 110 } # node B
      3: { p: 1, alpha: 1, theta: 0.8 } # node C
      4: { p: 0.1, alpha: 1, theta: 0.1 } # node D
      5: { p: 1, alpha: 1, theta: 1.8 } # node E
    2:
      connected: false
    3:
      connected: false

  events:
    smooth-step1:
      time: 5000
      node: 4
      action: remove
    smooth-step2:
      time: 5000
      node: 5
      action: remove
    smooth-step3:
      time: 5000
      node: 2
      action: add

  node_strategies:
    0: step

  filename_suffix: step

  debug: false


scenario32:
  numnodes: 6

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 } # node A
      2: { p: 0.01, alpha: 1, theta: 110 } # node B
      3: { p: 1, alpha: 1, theta: 0.8 } # node C
      4: { p: 0.1, alpha: 1, theta: 0.1 } # node D
      5: { p: 1, alpha: 1, theta: 1.8 } # node E
    2:
      connected: false
    3:
      connected: false

  events:
    smooth-step1:
      time: 5000
      node: 4
      action: remove
    smooth-step2:
      time: 5000
      node: 5
      action: remove
    smooth-step3:
      time: 5000
      node: 3
      action: add

  node_strategies:
    0: smooth

  filename_suffix: smooth

  debug: false


# A more complex, large scenario with many dynamics.
# Step is the clear winner here, then broadcast. Smooth is significantly worse.
complex1:

  numnodes: 21

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 2 }
      2: { p: 0.01, alpha: 1, theta: 110 }
      3: { p: 0.1, alpha: 1, theta: 1.8 }
      4: { p: 0.1, alpha: 2, theta: 0.4 }
      5: { p: 1, alpha: 1.5, theta: 0.2 }
      6: { p: 0.3, alpha: 1, theta: 2 }
      7: { p: 0.01, alpha: 1, theta: 110 }
      8: { p: 0.1, alpha: 1, theta: 0.5 }
      9: { p: 0.8, alpha: 1, theta: 0.4 }
      10: { p: 0.53, alpha: 1, theta: 5.8 }
      11: { p: 0.2, alpha: 1, theta: 2 }
      12: { p: 0.1, alpha: 1, theta: 10 }
      13: { p: 0.34, alpha: 1, theta: 2.8 }
      14: { p: 0.001, alpha: 2, theta: 0.4 }
      15: { p: 1, alpha: 1.5, theta: 1.1 }
      16: { p: 1, alpha: 1, theta: 0.01 }
      17: { p: 0.3, alpha: 5, theta: 11 }
      18: { p: 0.95, alpha: 1, theta: 0.2 }
      19: { p: 0.1, alpha: 1, theta: 5.54 }
      20: { p: 0.75, alpha: 7, theta: 8.8 }
    4:
      connected: false
    7:
      connected: false
    8:
      connected: false
    9:
      connected: false
    12:
      connected: false
    13:
      connected: false
    15:
      connected: false
    18:
      connected: false
    20:
      connected: false

  events:
    one:
      time: 300
      node: 4
      action: add
    two:
      time: 500
      node: 5
      action: remove
    three:
      time: 700
      node: 7
      action: add
    three-2:
      time: 700
      node: 8
      action: add
    four:
      time: 1800
      node: 9
      action: add
    five:
      time: 2000
      node: 14
      action: remove
    six:
      time: 2100
      node: 15
      action: add
    six-2:
      time: 2100
      node: 16
      action: remove
    seven:
      time: 3500
      node: 8
      action: remove
    eight:
      time: 3600
      node: 2
      action: remove
    eight-2:
      time: 3600
      node: 3
      action: remove
    nine:
      time: 3600
      node: 18
      action: add
    nine-2:
      time: 3600
      node: 17
      action: remove
    ten:
      time: 3800
      node: 19
      action: remove
    ten-2:
      time: 3800
      node: 4
      action: remove
    eleven:
      time: 4500
      node: 16
      action: add
    eleven-2:
      time: 4500
      node: 8
      action: add
    twelve:
      time: 5000
      node: 7
      action: remove
    thirteen:
      time: 5200
      node: 19
      action: add
    fourteen:
      time: 5500
      node: 6
      action: remove
    fifteen:
      time: 5800
      node: 2
      action: add
    sixteen:
      time: 5800
      node: 4
      action: add
    seventeen:
      time: 7400
      node: 15
      action: remove
    seventeen-2:
      time: 7400
      node: 16
      action: remove
    seventeen-3:
      time: 7400
      node: 6
      action: add
    seventeen-4:
      time: 7400
      node: 17
      action: add
    seventeen-5:
      time: 7400
      node: 19
      action: remove
    seventeen-6:
      time: 7400
      node: 8
      action: remove
    seventeen-7:
      time: 7400
      node: 14
      action: add
    eighteen:
      time: 6500
      node: 3
      action: add
    nineteen:
      time: 8100
      node: 14
      action: remove
    nineteen-2:
      time: 8100
      node: 3
      action: remove
    twenty:
      time: 8400
      node: 6
      action: remove
    twenty-2:
      time: 8400
      node: 19
      action: add
    twenty-one:
      time: 8800
      node: 10
      action: remove
    twenty-one-2:
      time: 8800
      node: 11
      action: remove
    twenty-two:
      time: 8400
      node: 14
      action: add
    twenty-three:
      time: 8400
      node: 18
      action: remove
    twenty-three-2:
      time: 8400
      node: 14
      action: remove
    twenty-three-3:
      time: 9300
      node: 10
      action: add

  node_strategies:
    0: step

  filename_suffix: step

  debug: false


complex2:

  numnodes: 21

  node_parameters:
    0:
      1: { p: 1, alpha: 1, theta: 0.8 }
      2: { p: 0.9, alpha: 1, theta: 0.9 }
      3: { p: 0.9, alpha: 1, theta: 0.8 }
      4: { p: 0.7, alpha: 2, theta: 1.0 }
      5: { p: 1, alpha: 1.5, theta: 0.85 }
      6: { p: 0.9, alpha: 1, theta: 1 }
      7: { p: 0.6, alpha: 1, theta: 1.2 }
      8: { p: 0.2, alpha: 1, theta: 0.5 }
      9: { p: 0.9, alpha: 1, theta: 0.9 }
      10: { p: 0.93, alpha: 1, theta: 18 }
      11: { p: 0.82, alpha: 1, theta: 1 }
      12: { p: 0.4, alpha: 1, theta: 1.3 }
      13: { p: 0.84, alpha: 1, theta: 1.1 }
      14: { p: 0.2, alpha: 2, theta: 0.4 }
      15: { p: 1, alpha: 1.5, theta: 1.1 }
      16: { p: 1, alpha: 1, theta: 0.01 }
      17: { p: 0.9, alpha: 5, theta: 1 }
      18: { p: 0.95, alpha: 1, theta: 0.8 }
      19: { p: 0.8, alpha: 1, theta: 1.54 }
      20: { p: 0.75, alpha: 7, theta: 0.8 }
    8:
      connected: false
    9:
      connected: false
    10:
      connected: false
    11:
      connected: false
    12:
      connected: false
    13:
      connected: false
    14:
      connected: false
    16:
      connected: false
    15:
      connected: false
    17:
      connected: false
    20:
      connected: false

  events:
    one:
      time: 2000
      node: 1
      action: remove
    two:
      time: 2000
      node: 2
      action: remove
    three:
      time: 2000
      node: 3
      action: remove
    three-a:
      time: 3000
      node: 4
      action: remove
    three-b:
      time: 3000
      node: 5
      action: remove
    three-c:
      time: 3000
      node: 6
      action: remove
    four:
      time: 6000
      node: 8
      action: add
    five:
      time: 6000
      node: 9
      action: add
    six:
      time: 6000
      node: 10
      action: add
    seven:
      time: 6000
      node: 11
      action: add
    eight:
      time: 6000
      node: 12
      action: add
    nine:
      time: 6000
      node: 13
      action: add
    ten:
      time: 6000
      node: 14
      action: add
    eleven:
      time: 6000
      node: 15
      action: add
    twelve:
      time: 6000
      node: 16
      action: add
    thirteen:
      time: 6000
      node: 17
      action: add
    fourteen:
      time: 7000
      node: 8
      action: remove
    fifteen:
      time: 7000
      node: 20
      action: add
    sixteen:
      time: 7100
      node: 9
      action: remove
    seventeen:
      time: 7100
      node: 10
      action: remove
    eighteen:
      time: 7100
      node: 12
      action: remove
    nineteen:
      time: 7100
      node: 13
      action: remove
    twenty:
      time: 7100
      node: 14
      action: remove
    twenty-one:
      time: 7100
      node: 15
      action: remove
    twenty-two:
      time: 7100
      node: 16
      action: remove
    twenty-three:
      time: 7100
      node: 17
      action: remove
    twenty-four:
      time: 7100
      node: 19
      action: remove


  node_strategies:
    0: step

  filename_suffix: step

  debug: false


complex3:

  numnodes: 21

  node_parameters:
    0:
      1: { p: 1, alpha: 3, theta: 1.8 }
      2: { p: 0.9, alpha: 3, theta: 0.2 }
      3: { p: 0.9, alpha: 0.2, theta: 0.1 }
      4: { p: 0.7, alpha: 2, theta: 1.0 }
      5: { p: 1, alpha: 5, theta: 1.5 }
      6: { p: 0.9, alpha: 2, theta: 0.6 }
      7: { p: 0.6, alpha: 1, theta: 1.8 }
      8: { p: 0.2, alpha: 4, theta: 1 }
      9: { p: 0.9, alpha: 2, theta: 0.2 }
      10: { p: 0.93, alpha: 1.3, theta: 1 }
      11: { p: 0.82, alpha: 5, theta: 7 }
      12: { p: 0.4, alpha: 9, theta: 1.3 }
      13: { p: 0.84, alpha: 0.4, theta: 1.2 }
      14: { p: 0.2, alpha: 1, theta: 1.1 }
      15: { p: 1, alpha: 1.2, theta: 1 }
      16: { p: 1, alpha: 1, theta: 1.6 }
      17: { p: 0.9, alpha: 3, theta: 1 }
      18: { p: 0.95, alpha: 1, theta: 2.2 }
      19: { p: 0.8, alpha: 2, theta: 0.4 }
      20: { p: 0.75, alpha: 1, theta: 3.2 }
    1:
      connected: false
    2:
      connected: false
    3:
      connected: false
    4:
      connected: false
    5:
      connected: false
    6:
      connected: false
    7:
      connected: false
    8:
      connected: false
    9:
      connected: false
    10:
      connected: false

  events:
    one:
      time: 1000
      node: 1
      action: add
    two:
      time: 1100
      node: 11
      action: remove
    three:
      time: 2200
      node: 3
      action: add
    three-a:
      time: 2200
      node: 14
      action: remove
    three-b:
      time: 2200
      node: 5
      action: add
    three-c:
      time: 2200
      node: 6
      action: remove
    four:
      time: 3100
      node: 8
      action: add
    five:
      time: 3300
      node: 9
      action: add
    six:
      time: 4000
      node: 10
      action: add
    seven:
      time: 4400
      node: 11
      action: add
    eight:
      time: 5000
      node: 12
      action: remove
    nine:
      time: 6000
      node: 13
      action: remove
    ten:
      time: 6100
      node: 14
      action: add
    eleven:
      time: 6200
      node: 15
      action: remove
    twelve:
      time: 6300
      node: 16
      action: remove
    thirteen:
      time: 6400
      node: 17
      action: remove
    fourteen:
      time: 7000
      node: 8
      action: remove
    fifteen:
      time: 7100
      node: 20
      action: remove
    sixteen:
      time: 7200
      node: 9
      action: remove
    seventeen:
      time: 7300
      node: 10
      action: remove
    eighteen:
      time: 7400
      node: 12
      action: add
    nineteen:
      time: 7500
      node: 17
      action: add
    twenty:
      time: 7800
      node: 6 
      action: add
    twenty-one:
      time: 7900
      node: 15
      action: add
    twenty-two:
      time: 8100
      node: 3
      action: remove
    twenty-three:
      time: 8300
      node: 5 
      action: remove
    twenty-four:
      time: 9000
      node: 19
      action: remove

  debug: false


complex4:

  numnodes: 21

  node_parameters:
    0:
      1: { p: 0.1, alpha: 1, theta: 8.0 }
      2: { p: 0.6, alpha: 1, theta: 2.0 }
      3: { p: 0.8, alpha: 2, theta: 1.0 }
      4: { p: 0.2, alpha: 1, theta: 1.0 }
      5: { p: 1, alpha: 2, theta: 1.0 }
      6: { p: 0.2, alpha: 1, theta: 2.0 }
      7: { p: 0.1, alpha: 3, theta: 1.7 }
      8: { p: 0.4, alpha: 2, theta: 0.1 }
      9: { p: 0.5, alpha: 1, theta: 0.5 }
      10: { p: 0.9, alpha: 3, theta: 2.0 }
      11: { p: 0.2, alpha: 5, theta: 1.1 }
      12: { p: 0.1, alpha: 9, theta: 1.9 }
      13: { p: 0.4, alpha: 4, theta: 1.0 }
      14: { p: 0.5, alpha: 1, theta: 1.2 }
      15: { p: 0.8, alpha: 2, theta: 2.1 }
      16: { p: 0.1, alpha: 1, theta: 1.0 }
      17: { p: 0.7, alpha: 1, theta: 1.0 }
      18: { p: 0.5, alpha: 1, theta: 0.2 }
      19: { p: 0.8, alpha: 1, theta: 1.1 }
      20: { p: 0.7, alpha: 1, theta: 3.1 }
    1:
      connected: false
    3:
      connected: false
    8:
      connected: false
    11:
      connected: false
    12:
      connected: false
    17:
      connected: false

  events:
    one:
      time: 500
      node: 1
      action: add
    two:
      time: 1000
      node: 11
      action: add
    three:
      time: 1200
      node: 3
      action: add
    three-a:
      time: 1200
      node: 13
      action: remove
    three-b:
      time: 1200
      node: 5
      action: remove
    three-c:
      time: 1200
      node: 2
      action: remove
    four:
      time: 3000
      node: 8
      action: add
    five:
      time: 3300
      node: 9
      action: remove
    six:
      time: 3500
      node: 10
      action: remove
    seven:
      time: 3600
      node: 18
      action: remove
    eight:
      time: 4000
      node: 15
      action: remove
    nine:
      time: 3400
      node: 16
      action: remove
    ten:
      time: 4100
      node: 7
      action: remove
    eleven:
      time: 5200
      node: 14
      action: remove
    twelve:
      time: 6000
      node: 13
      action: add
    thirteen:
      time: 6400
      node: 17
      action: remove
    fourteen:
      time: 7000
      node: 8
      action: remove
    fifteen:
      time: 7100
      node: 20
      action: remove
    sixteen:
      time: 7500
      node: 9
      action: add
    seventeen:
      time: 7800
      node: 10
      action: add
    eighteen:
      time: 7400
      node: 13
      action: remove
    nineteen:
      time: 7500
      node: 17
      action: add
    twenty:
      time: 7800
      node: 1 
      action: remove
    twenty-one:
      time: 7900
      node: 9
      action: remove
    twenty-two:
      time: 8500
      node: 2
      action: add
    twenty-three:
      time: 8900
      node: 10 
      action: remove
    twenty-four:
      time: 9200
      node: 1
      action: add

  debug: false
